<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>UCustomPrefabsAPI</AssemblyName>
    <Description>Universal Custom Prefabs API For Unity Games</Description>
    <Version>0.0.1</Version>
    <LangVersion>latest</LangVersion>
	 <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>
  
  <PropertyGroup>
    <RestoreSources>$(RestoreSources);https://api.nuget.org/v3/index.json;https://nuget.bepinex.dev/v3/index.json</RestoreSources>
  </PropertyGroup>
	
  <PropertyGroup>
	<RootNamespace>UCustomPrefabsAPI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.2" IncludeAssets="compile" />
	  <PackageReference Include="UnityEngine.Modules" Version="6000.0.*" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Build\" />
  </ItemGroup>

  <PropertyGroup>
    <DebugPluginDir>D:\SteamLibrary\steamapps\common\PEAK\BepInEx\plugins</DebugPluginDir>
  </PropertyGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /Y &quot;$(TargetDir)$(ProjectName).dll&quot; &quot;$(DebugPluginDir)&quot; &#xD;&#xA;" />
    <Exec Command="copy /Y &quot;$(TargetDir)$(ProjectName).pdb&quot; &quot;$(DebugPluginDir)&quot; &#xD;&#xA;" />
		<Exec Command="copy /Y &quot;$(TargetDir)$(ProjectName).dll&quot; &quot;$(ProjDir)Build&quot; &#xD;&#xA;" />
	</Target>
	
</Project>
